### ISSUE TITLE
How to define and use storm metrics ?

### ISSUE THREAD

**Issue by tinduong94** [Parsely/streamparse#387]
I want to use storm metrics to monitor the performance of spouts and bolts but didn't figure out the way. Any help on this ?

**Comment by dan-blanchard** [comment]
I have not actually done this myself, but there's documentation [here](https://pystorm.readthedocs.io/en/latest/api.html#pystorm.component.Component.report_metric). (The "Note" part was previously missing due to a typo in the docstring, but I fixed that.)

**Comment by tinduong94** [comment]
Thanks @dan-blanchard 
Actually I've already seen that API, and still the same question remains. Anyone know how to register the metric in Python ?

**Comment by dan-blanchard** [comment]
@tinduong94 There is no way to define/register it from Python, because there is no Storm Multilang API call for it, and there's no Thrift method we could use either.

**Comment by ivanalikin-saritasa** [comment]
@tinduong94 Is `report_metric` function Streamparse's replacement for Storm native metrics? Will calls to it be reflected in Storm UI?

**Comment by dan-blanchard** [comment]
@ivanalikin-saritasa If you write the Java code to register the metrics, they will appear. I've just never tried to do that part. `report_metric` will pass the appropriate Storm Multilang messages to Storm to report them, but unless they're registered, I don't believe they'll show up. @HeartSaVioR might be able to answer that one though.
